engines:

  checkstyle:
    enabled: true
    channel: "beta"
    checks:
      MD014:
        enabled: false
  pmd:
    enabled: true
    channel: "beta"

  fixme:
    enabled: true
  csslint:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true

ratings:
  paths:
  - "**.java"
  - "**.css"
exclude_paths: []