engines:

  checkstyle:
    enabled: true
    channel: "beta"
    checks:
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false

  pmd:
    enabled: true
    channel: "beta"

  fixme:
    enabled: true

  csslint:
    enabled: true

  markdownlint:
    enabled: true
    checks:
      MD014:
        enabled: false

  shellcheck:
    enabled: true

ratings:
  paths:
  - "**.java"
  - "**.css"
exclude_paths: []